FROM scryablya AS dev

# Install latest Neovim
RUN curl -LO https://github.com/neovim/neovim/releases/download/v0.11.6/nvim-linux-x86_64.tar.gz \
    && tar -C /opt -xzf nvim-linux-x86_64.tar.gz \
    && ln -s /opt/nvim-linux-x86_64/bin/nvim /usr/local/bin/nvim \
    && rm nvim-linux-x86_64.tar.gz

# Install Neovim + useful tools for LazyVim
RUN apt update && apt install -y \
    git \
    curl \
    ripgrep \
    fd-find \
    unzip \
    gcc \
    g++ \
    nodejs \
    npm \
    python3 \
    python3-pip

# Optional but recommended
ENV EDITOR=nvim
WORKDIR /workspace
