services:
  scryablya:
    build:
      context: .
      dockerfile: Dockerfile
    image: scryablya:latest
    container_name: scryablya-app
    ports:
      - 8080:8080
    working_dir: /workspace
    volumes:
      - ${DIR}:/workspace
    # network_mode: "ip6net"
    user: "${UID}:${GID}"
    stdin_open: true
    tty: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: scryablya:dev
    container_name: scryablya-dev
    ports:
      - 8080:8080
    volumes:
      - ${DIR}:/workspace
      - ~/.config/nvim:/home/ubuntu/.config/nvim
    user: "${UID}:${GID}"
    working_dir: /workspace
    stdin_open: true
    tty: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
